### ISSUE TITLE
Проблема с непредсказуемыми падениями. 

### ISSUE THREAD

**Issue by innovait-rus** [ltfriend/AndroidScannerDriverFor1C#2]
Долго описывать причину. Но везде где создаётся строка jni её надо за собой подчищать. Иначе сборщик мусора может не справился и произойдет переполнение стэка.

 std::wstring wManufacturer = ToWStringJni(jManufacturer);

env->DeleteLocalRef(jManufacturer);

**Comment by ltfriend** [comment]
Спасибо за замечание. Внесены исправления.
